Vagrant.configure(2) do |config|
    config.vm.box = "bento/ubuntu-16.04"
    config.vm.synced_folder "./", "/home/vagrant/project/"
    config.vm.network "private_network", ip: "3.3.3.2", auto_config: false
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end

    # manual ip
    config.vm.provision "shell", run: "always", inline: "ifconfig eth1 3.3.3.2 netmask 255.255.255.0 up"

    config.vm.provision "shell", run: "once", inline: <<-SHELL
        bash /home/vagrant/project/install-docker.sh
    SHELL
end
