"""add model user

Revision ID: 06434fdf2981
Revises: b532f1bb7c83
Create Date: 2021-05-09 10:31:03.259554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06434fdf2981'
down_revision = 'b532f1bb7c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
