version: '3.8'
services:

  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db_name
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
